=== tradefurniturecompany/site/app/code/Hotlink/Framework/etc/hotlink.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        <xs:complexType name="declaration" mixed="true">
            <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="lax" />
            </xs:sequence>
            <xs:attribute name="id" type="xs:token" use="required"/>
            <xs:attribute name="class" type="xs:string" use="required"/>
        </xs:complexType>
        -->
    <xs:element name="hotlink">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="platform">
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="interaction">
                                <xs:complexType>
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name="trigger">
                                            <xs:complexType>
                                                <xs:attribute name="class" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="monitor">
                                            <xs:complexType>
                                                <xs:attribute name="class" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="action">
                                            <xs:complexType>
                                                <xs:attribute name="class" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="implementation">
                                          <xs:complexType>
                                            <xs:attribute name="class" type="xs:string" use="required"/>
                                          </xs:complexType>
                                        </xs:element>
                                    </xs:choice>
                                    <xs:attribute name="class" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                        <xs:attribute name="class" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== tradefurniturecompany/site/app/code/Hotlink/Framework/Test/integration/Model/Config/MapTest/module1/etc/hotlink.xml
<?xml version="1.0"?>
<hotlink xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Hotlink_Framework:etc/hotlink.xsd">
    <platform class="\Hotlink\Framework\Model\Platform">
        <interaction class="\Hotlink\Framework\Model\Interaction\Log\Cleaning">
            <trigger class="\Hotlink\Framework\Model\Trigger\Monitor\Cron" />
            <monitor class="\Hotlink\Framework\Model\Monitor\Cron" />
            <action class="\Hotlink\Framework\Model\Action\Index" />
        </interaction>
        <interaction class="\Hotlink\Framework\Module1\InteractionA">
            <trigger class="\Hotlink\Framework\Model\Trigger\Monitor\Cron" />
            <monitor class="\Hotlink\Framework\Model\Monitor\Cron" />
            <monitor class="\Hotlink\Framework\Model\Monitor\OrderStatus" />
            <monitor class="\Hotlink\Framework\Model\Monitor\LostItems" />
        </interaction>
        <interaction class="\Hotlink\Framework\Module1\InteractionB">
            <trigger class="\Hotlink\Framework\Model\Trigger\Monitor\Cron" />
            <monitor class="\Hotlink\Framework\Model\Monitor\Cron" />
            <monitor class="\Hotlink\Framework\Model\Monitor\OrderStatus" />
            <action class="\Hotlink\Framework\Model\Action\Index" />
        </interaction>
    </platform>
</hotlink>
